name: Action for PRs
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
